version: '2'

volumes:
    logs:
        driver: local
    data:
        
services:
    slim:
        build:
            context: ./
            dockerfile: Dockerfile

        working_dir: /var/www
        command: php -S 0.0.0.0:8081 -t ./
        environment:
            docker: "true"
        ports:
            - 8080:8081
        volumes:
            - .:/var/www

    database:
        image: mysql:5.7
        restart: always
        volumes:
          - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin

    adminer:
        image: adminer
        restart: always
        ports:
          - 3307:8080


